export const ARTICLES: Record<string, { section: string; htmlContent: string }> = {
  "Quick Start Guide": {
    section: "Getting Started",
    htmlContent: `<p>Get your Vexel store live in under 15 minutes.</p><h2>Overview</h2><ol><li>Access your Customer Portal</li><li>Download your theme</li><li>Install the theme in Shopify</li><li>Activate your license</li><li>Customize and launch</li></ol><h2>Step 1: Access Your Customer Portal</h2><p>Log in to your account on this site using your license key from your purchase confirmation email.</p><h2>Step 2: Download Your Theme</h2><ol><li>You'll see your license listed</li><li>Click the <strong>Download Theme</strong> button</li><li>A ZIP file will download to your computer</li></ol><p><strong>Important:</strong> Keep this ZIP file — you'll upload it to Shopify in the next step.</p><h2>Step 3: Install in Shopify</h2><ol><li>Log in to your Shopify Admin</li><li>Go to <strong>Online Store → Themes</strong></li><li>Click <strong>Add theme → Upload zip file</strong></li><li>Select the Vexel ZIP file you downloaded</li><li>Wait for the upload to complete</li></ol><h2>Step 4: Activate Your License</h2><ol><li>Click <strong>Customize</strong> on your Vexel theme</li><li>Click <strong>Theme settings</strong> (gear icon at bottom left)</li><li>Find the <strong>License</strong> section</li><li>Enter your License Key</li><li>Click <strong>Save</strong></li></ol><h2>Step 5: Customize and Launch</h2><ul><li>Set your brand colors in Theme Settings</li><li>Upload your logo</li><li>Add your products to the product grids</li><li>Configure the AI chatbot with your selling points</li></ul><p>Go to <strong>Online Store → Themes</strong> and click <strong>Publish</strong>. Your store is live!</p>`,
  },
  "Downloading Your Theme": {
    section: "Getting Started",
    htmlContent: `<p>After purchasing Vexel, download the theme files to install in your Shopify store.</p><h2>Where to Download</h2><ol><li>Go to your account page on this site</li><li>Log in with your license key</li><li>Click the <strong>Download Theme</strong> button</li></ol><p>A ZIP file will download to your computer.</p><h2>Common Download Issues</h2><h3>"Forbidden" Error</h3><ul><li>Make sure you are logged in with a valid license key</li><li>Try logging out and back in</li><li>Clear your browser cache and try again</li><li>Try a different browser</li></ul><h3>Download Keeps Failing</h3><ul><li>Check your internet connection</li><li>Disable browser extensions</li><li>Try right-clicking the button and selecting "Save link as..."</li></ul><h2>After Downloading</h2><p><strong>Don't unzip it</strong> — Shopify needs the ZIP file as-is. Go to Shopify Admin → Online Store → Themes → Add theme → Upload zip file. You can re-download as many times as you need.</p>`,
  },
  "Installing in Shopify": {
    section: "Getting Started",
    htmlContent: `<p>This guide walks you through uploading and installing your Vexel theme in Shopify.</p><h2>Prerequisites</h2><ul><li>Downloaded the Vexel ZIP file from your account</li><li>Access to your Shopify Admin</li><li>Your license key ready</li></ul><h2>Step-by-Step Installation</h2><h3>1. Log in to Shopify Admin</h3><p>Go to: <code>https://YOUR-STORE.myshopify.com/admin</code></p><h3>2. Navigate to Themes</h3><p>In the left sidebar click <strong>Online Store → Themes</strong>.</p><h3>3. Upload the Theme</h3><ol><li>Click <strong>Add theme → Upload zip file</strong></li><li>Select the Vexel ZIP file</li><li>Wait for the upload to complete (30–60 seconds)</li></ol><h3>4. Verify Installation</h3><p>The Vexel theme will appear in your Theme library as "Unpublished."</p><h2>Common Issues</h2><ul><li><strong>Upload failed:</strong> Make sure the file is the original ZIP, not unzipped</li><li><strong>Theme not appearing:</strong> Refresh the page and try again</li></ul><h2>Updating Your Theme</h2><p>When we release updates: download the new version, upload as a new theme (don't overwrite), customize, then publish when ready. This ensures you can always roll back.</p>`,
  },
  "After Your Purchase": {
    section: "Getting Started",
    htmlContent: `<p>Congratulations on purchasing Vexel! Here's what happens next.</p><h2>Your License Key</h2><p>You'll receive a confirmation email with your license key: <code>XXXX-XXXX-XXXX-XXXX</code>. Keep it safe — you need it to activate your theme and log into the portal.</p><h2>What You Receive</h2><h3>Vexel Lite ($179)</h3><ul><li>Full Vexel theme (ZIP file)</li><li>1 store license — transfer to a new store if banned</li><li>Product image generator</li><li>Product list generator</li><li>Built-in setup support &amp; complete documentation</li><li>Lifetime updates</li></ul><h3>Vexel Pro ($379)</h3><ul><li>Everything in Lite, plus:</li><li>1-on-1 full store setup call</li><li>5 store licenses — use on 5 stores simultaneously</li><li>Private Vexel community access</li></ul><h2>Didn't Receive Anything?</h2><ul><li>Check your spam/junk folder</li><li>Wait up to 10 minutes</li><li>Make sure you're checking the right email address</li></ul><p>If it's been 30+ minutes, contact support via the chat widget with your purchase email and we'll resend your license key.</p><h2>Pro: 1-on-1 Setup</h2><p>Pro customers get a full store setup session. You'll receive an email to schedule a time after purchase. Haven't received scheduling info? Contact support!</p>`,
  },
  "Understanding Your License": {
    section: "License & Domain",
    htmlContent: `<p>Your Vexel license key activates and protects your Shopify theme.</p><h2>How Licenses Work</h2><p>Each Vexel Lite license is valid for one Shopify store. When you activate it, it becomes permanently linked to that store's auto-generated domain. Pro licenses work on up to 5 stores.</p><h2>Domain Locking</h2><p>Your license locks to your store's <strong>auto-generated</strong> Shopify domain — the one with random letters and numbers:</p><ul><li>✅ Locked to: <code>z6txxs-04.myshopify.com</code> (has numbers — correct)</li><li>❌ NOT to: <code>mystore.myshopify.com</code> (custom, no numbers)</li><li>❌ NOT to: <code>yourcustomdomain.com</code> (custom domain)</li></ul><p>This means you can change your custom domains anytime without affecting your license!</p><h2>What the License Unlocks</h2><p>Without a valid license, the theme shows a setup modal. With an active license, you get all premium sections, AI chatbot, spin wheel, bundle builder, urgency elements, and all other features.</p><h2>License Key Format</h2><p>Your key: <code>XXXX-XXXX-XXXX-XXXX</code> — four groups of 4 characters separated by dashes.</p><h2>Transferring Your License</h2><ul><li><strong>Pro:</strong> Unlimited domain changes</li><li><strong>Lite:</strong> One free domain change (e.g., if banned)</li></ul>`,
  },
  "Auto-Generated Shopify Domains": {
    section: "License & Domain",
    htmlContent: `<p>This is the most important concept to understand. Many support issues come from confusion about this!</p><h2>The Three Types of Domains</h2><h3>1. Auto-Generated Domain ✅ (Required for Vexel)</h3><p>Shopify creates this automatically when you make a store: <code>z6txxs-04.myshopify.com</code>. It contains random letters AND numbers, can never be changed, and is what Vexel needs for license activation.</p><h3>2. Custom myshopify.com Domain ❌</h3><p>Shopify lets you change your subdomain to something readable like <code>mystore.myshopify.com</code>. This won't work for Vexel because it can be changed.</p><h3>3. Custom Domain ❌</h3><p>A domain you purchase like <code>yourcoolstore.com</code>. Not used for license activation.</p><h2>Simple Rule</h2><p><strong>If it has random numbers mixed with letters, it's the right one!</strong></p><ul><li>✅ <code>z6txxs-04.myshopify.com</code> — has numbers, correct</li><li>❌ <code>mystore.myshopify.com</code> — no numbers, wrong</li></ul><h2>How to Find It</h2><ol><li>Go to <strong>Shopify Admin → Settings → Domains</strong></li><li>Look for the domain with random letters and numbers</li></ol><p><strong>"My customers use my custom domain — will the theme work?"</strong> Yes! Your custom domain is completely separate. Customers see your custom domain and the theme works perfectly.</p>`,
  },
  "License Activation Step-by-Step": {
    section: "License & Domain",
    htmlContent: `<p>Follow these exact steps to activate your Vexel license.</p><h2>Before You Start</h2><ul><li>✅ Theme downloaded and installed in Shopify</li><li>✅ Your license key ready</li><li>✅ Know your auto-generated domain (has numbers like <code>z6txxs-04.myshopify.com</code>)</li></ul><h2>Steps</h2><h3>Step 1: Open Theme Customizer</h3><p>Shopify Admin → Online Store → Themes → Vexel → <strong>Customize</strong></p><h3>Step 2: Open Theme Settings</h3><p>Click the gear icon ⚙️ at the bottom left for "Theme settings."</p><h3>Step 3: Find the License Section</h3><p>In Theme Settings, scroll to find <strong>License</strong>. Click to expand.</p><h3>Step 4: Enter Your Key</h3><p>Paste your license key: <code>XXXX-XXXX-XXXX-XXXX</code>. No extra spaces.</p><h3>Step 5: Save</h3><p>Click <strong>Save</strong>. The theme validates your license and all premium sections load!</p><h2>Troubleshooting</h2><ul><li><strong>"Invalid License Key"</strong> — Check you copied the full key with no spaces</li><li><strong>"Domain Mismatch"</strong> — License is on a different store. Contact support to transfer.</li><li><strong>Changes not appearing</strong> — Make sure you clicked Save, then refresh the page</li></ul>`,
  },
  "Finding Your Auto-Generated Domain": {
    section: "License & Domain",
    htmlContent: `<p>For Vexel activation, you need your auto-generated Shopify domain — the one with random letters and numbers.</p><h2>What You're Looking For</h2><p>It looks like: <code>z6txxs-04.myshopify.com</code>. Key identifier: random letters AND numbers mixed together.</p><h2>How to Find It</h2><ol><li>Go to <strong>Shopify Admin</strong></li><li>Click <strong>Settings</strong> (bottom left)</li><li>Click <strong>Domains</strong></li><li>Find the domain with random letters and numbers ending in <code>.myshopify.com</code></li></ol><h2>Common Mistakes</h2><ul><li>❌ <code>mystore.myshopify.com</code> — no numbers, wrong</li><li>❌ <code>mycoolstore.com</code> — custom domain, wrong</li><li>❌ <code>https://z6txxs-04.myshopify.com</code> — don't include https://</li><li>❌ <code>z6txxs-04.myshopify.com/</code> — no trailing slash</li><li>✅ <code>z6txxs-04.myshopify.com</code> — correct!</li></ul><h2>Still Can't Find It?</h2><ul><li>Check your Shopify welcome email (it often has your original domain)</li><li>Contact Shopify Support — they can confirm your store's original domain</li><li>Use the chat widget here and we'll help you find it</li></ul>`,
  },
  "Activated on Wrong Domain?": {
    section: "License & Domain",
    htmlContent: `<p>Accidentally activated your license on the wrong Shopify store? Here's what to do.</p><h2>Understanding the Issue</h2><p>When you activate your Vexel license, it locks to that store's auto-generated domain. A domain transfer is needed to switch it to another store.</p><h2>Common Scenarios</h2><ul><li>Activated on a test store instead of your real store</li><li>Typo in the domain during activation</li><li>Created a new store after your old one was banned</li></ul><h2>How to Transfer</h2><p>Contact support via the chat widget on this page. Provide:</p><ul><li>Your license key</li><li>The current (wrong) domain</li><li>The new (correct) auto-generated domain (with numbers)</li></ul><p>We'll process the transfer quickly.</p><h2>Transfer Limits</h2><ul><li><strong>Vexel Pro:</strong> Unlimited domain transfers</li><li><strong>Vexel Lite:</strong> One free domain transfer included</li></ul><h2>Prevention</h2><p>Before activating, always confirm you're on the correct Shopify store and using the auto-generated domain (with numbers, not a readable name).</p>`,
  },
  "Custom Domains and Your License": {
    section: "License & Domain",
    htmlContent: `<p>"Do I need to worry about my custom domain affecting my license?" — No. Here's why.</p><h2>Custom Domains Are Completely Separate</h2><p>Your Vexel license is locked to your auto-generated Shopify domain (like <code>z6txxs-04.myshopify.com</code>). Custom domains have nothing to do with it.</p><p>This means:</p><ul><li>✅ Add custom domains anytime</li><li>✅ Remove custom domains anytime</li><li>✅ Change your primary custom domain</li><li>✅ Change your custom myshopify.com name (e.g., <code>mystore.myshopify.com</code>)</li><li>✅ None of this affects your Vexel license</li></ul><h2>Why We Use the Auto-Generated Domain</h2><p>Your auto-generated domain (<code>z6txxs-04.myshopify.com</code>) can <em>never</em> be changed. Custom domains and custom myshopify names can change, so they're not reliable for license locking.</p><h2>What Customers See</h2><p>Customers see your custom domain. Behind the scenes, Vexel validates using your auto-generated domain. It's completely seamless.</p><h2>Adding a Custom Domain</h2><p>Shopify Admin → Settings → Domains → "Connect existing domain." Your Vexel theme continues working throughout this process.</p>`,
  },
  "Colors & Branding Setup": {
    section: "Theme Customization",
    htmlContent: `<p>Make Vexel your own by customizing colors, logo, and brand identity.</p><h2>Accessing Theme Settings</h2><ol><li><strong>Shopify Admin → Online Store → Themes</strong></li><li>Click <strong>Customize</strong> on your Vexel theme</li><li>Click the gear icon ⚙️ at bottom left for "Theme settings"</li></ol><h2>Main Color Options</h2><ul><li><strong>Primary Accent Color:</strong> Buttons, links, highlights, CTAs</li><li><strong>Secondary Accent Color:</strong> Gradient effects, hover states</li><li><strong>Background Color:</strong> Main page background (default: dark)</li><li><strong>Text Color:</strong> Body text (default: white for dark theme)</li><li><strong>Card Background:</strong> Cards and elevated elements</li></ul><h2>Logo Setup</h2><p>Go to <strong>Theme Settings → Logo</strong> and upload your logo image.</p><ul><li>Recommended size: 200–400px wide</li><li>PNG with transparent background works best</li><li>Keep file size under 500KB for fast loading</li></ul><h2>Social Links</h2><p>Add Instagram, TikTok, and Discord URLs in Theme Settings. They appear in your footer.</p><h2>Tips</h2><ul><li>Use 2–3 colors maximum for a clean look</li><li>Ensure text is readable against backgrounds</li><li>Preview on mobile to check colors on smaller screens</li><li><strong>Pro customers:</strong> Ask during your 1-on-1 setup call!</li></ul>`,
  },
  "Accessing the Theme Editor": {
    section: "Theme Customization",
    htmlContent: `<p>The Shopify Theme Editor is where you customize your Vexel theme visually.</p><h2>How to Open It</h2><ol><li>Go to <strong>Shopify Admin</strong></li><li>Click <strong>Online Store → Themes</strong></li><li>Find the Vexel theme and click <strong>Customize</strong></li></ol><h2>Editor Layout</h2><ul><li><strong>Left sidebar:</strong> Sections list. Click any section to edit it.</li><li><strong>Center:</strong> Live preview of your store. Changes appear in real-time.</li><li><strong>Bottom left — gear ⚙️:</strong> Global settings (colors, branding, license)</li><li><strong>Top bar:</strong> Page selector, device preview toggle, undo/redo, save</li></ul><h2>Adding Sections</h2><p>Click <strong>Add section</strong> in the left sidebar, choose a section type, and drag to reorder.</p><h2>Saving Changes</h2><p><strong>Always click Save in the top right corner!</strong> Changes are not saved automatically. If you leave without saving, your changes are lost.</p><h2>Preview vs. Publish</h2><ul><li><strong>Save:</strong> Saves to your theme but not live yet if unpublished</li><li><strong>Publish:</strong> Makes the theme live on your store</li></ul><h2>Mobile Preview</h2><p>Click the device icons at the top to preview mobile, tablet, and desktop. Most customers shop on phones — always check mobile!</p>`,
  },
  "Changing Theme Language": {
    section: "Theme Customization",
    htmlContent: `<p>Want to use Vexel in a different language? Here's how.</p><h2>Changing Text in Theme Editor</h2><ol><li>Open <strong>Theme Editor</strong> (Customize)</li><li>Click on any section</li><li>Find text fields (headlines, button text, descriptions)</li><li>Change to your preferred language</li><li>Click <strong>Save</strong></li></ol><h2>Shopify Language Settings</h2><p>For standard e-commerce terms (Add to Cart, Checkout, etc.):</p><ol><li>Go to <strong>Shopify Admin → Online Store → Themes</strong></li><li>Click <strong>···</strong> on your Vexel theme</li><li>Select <strong>Edit default theme content</strong></li><li>Find and update text strings</li><li>Save</li></ol><h2>Full Translations</h2><p>For complete translations, use apps like <strong>Weglot</strong>, <strong>Langify</strong>, or <strong>Translation Lab</strong> from the Shopify App Store. These handle automatic translation and multi-language stores.</p><h2>RTL Languages</h2><p>For Arabic, Hebrew, etc.: Vexel supports RTL layouts. Enable RTL in Shopify language settings and the theme adjusts automatically.</p>`,
  },
  "AI Chatbot Setup": {
    section: "Feature Guides",
    htmlContent: `<p>The Vexel AI chatbot helps you sell 24/7 by answering customer questions automatically.</p><h2>Enabling the Chatbot</h2><ol><li>Go to <strong>Theme Settings</strong> (gear icon)</li><li>Find the <strong>Chatbot</strong> section</li><li>Toggle <strong>Enable chatbot</strong> ON</li><li>Save</li></ol><h2>Key Settings</h2><h3>Chatbot Name</h3><p>Give your chatbot a name: "Sales Assistant," your brand name, or a custom name like "Alex."</p><h3>Custom Context (Most Important!)</h3><p>Tell the chatbot about your products. Example:</p><p><em>We sell premium vendor lists for resellers. Each list includes 30+ verified vendors with contact info. Customers get instant access after purchase. We offer 24/7 support and a 30-day guarantee.</em></p><h3>Key Selling Points</h3><p>Add bullet points the chatbot emphasizes: "Instant delivery," "30-day guarantee," "Trusted by 1000+ resellers."</p><h2>Tips for Better Results</h2><ul><li><strong>Be specific:</strong> Name your products, vendors, and features</li><li><strong>Include pricing</strong> so it can answer price questions</li><li><strong>Address objections:</strong> "Is this legit?", "What if it doesn't work?"</li><li><strong>Update it</strong> whenever you change prices or add products</li></ul><h2>Not Appearing?</h2><ul><li>Check it's enabled and saved</li><li>Is your license activated?</li><li>Clear browser cache</li></ul>`,
  },
  "Spin Wheel Setup": {
    section: "Feature Guides",
    htmlContent: `<p>The spin wheel is a gamified popup that captures emails and gives visitors discount codes.</p><h2>Enabling</h2><ol><li>Go to Home page in theme editor</li><li>Find the <strong>Spin Wheel</strong> section</li><li>Configure settings and Save</li></ol><h2>Basic Settings</h2><ul><li><strong>Show Delay:</strong> Wait before showing (5–10 seconds recommended)</li><li><strong>Exit Intent:</strong> Show when visitors are about to leave</li><li><strong>Re-show Frequency:</strong> Days before showing again (e.g., 7 = weekly)</li></ul><h2>Prize Segments</h2><p>For each segment, set: Text (e.g., "10% OFF"), Discount Code, Probability (1–100), and whether it's a winner.</p><p>Example: 10% OFF (30% chance) + Try Again (25%) + 20% OFF (15%) + FREE SHIPPING (10%)</p><h2>Creating Discount Codes</h2><p><strong>Create codes in Shopify FIRST:</strong> Shopify Admin → Discounts → Create discount → Discount code. Copy the exact code and paste it into the spin wheel settings.</p><h2>Form Fields</h2><p>Always collect email — that's the main goal. Optionally also collect name and phone.</p>`,
  },
  "Bundle Builder Setup": {
    section: "Feature Guides",
    htmlContent: `<p>The bundle builder lets customers create product bundles and receive automatic discounts. Great for increasing average order value!</p><h2>How It Works</h2><ol><li>Customers select multiple products</li><li>Savings increase as they add more</li><li>Discount codes are automatically applied at checkout</li></ol><h2>Setting Up</h2><ol><li>Go to Home page in theme editor</li><li>Find the <strong>Bundle Builder</strong> section</li><li>Configure tiers and Save</li></ol><h2>Tier Configuration</h2><ul><li><strong>Tier 1:</strong> e.g., "Buy 2" → 10% off → Code: BUNDLE10</li><li><strong>Tier 2:</strong> e.g., "Buy 3+" → 20% off → Code: BUNDLE20</li></ul><h2>Creating Discount Codes in Shopify</h2><p>Create BUNDLE10 and BUNDLE20 in <strong>Shopify Admin → Discounts → Create discount → Discount code</strong>. Paste the exact codes into your Vexel settings.</p><h2>Best Practices</h2><ul><li>Tier 1: Small discount (5–10%)</li><li>Tier 2: Noticeably better (15–25%)</li><li>Bundle complementary products</li><li>Show savings clearly to motivate adding more items</li></ul>`,
  },
  "Urgency Elements Setup": {
    section: "Feature Guides",
    htmlContent: `<p>Urgency elements create FOMO and encourage faster purchasing decisions.</p><h2>Available Elements</h2><ul><li><strong>Live Viewer Count</strong> — "X people viewing this"</li><li><strong>Recent Sales Notifications</strong> — Popup showing recent purchases</li><li><strong>Countdown Timer</strong> — Limited time offer countdown</li></ul><h2>Enabling</h2><ol><li>Go to <strong>Theme Settings</strong> (gear icon)</li><li>Find the <strong>Urgency</strong> section</li><li>Toggle each element ON/OFF</li><li>Configure timing and Save</li></ol><h2>Recommended Timing for Sales Notifications</h2><ul><li>Initial delay: 5 seconds</li><li>Show duration: 4 seconds</li><li>Min delay between popups: 8 seconds</li><li>Max delay: 15 seconds</li></ul><p>This creates natural-feeling, random intervals.</p><h2>Best Practices</h2><ul><li>Use 1–2 urgency elements, not all at once</li><li>Make numbers feel realistic</li><li>Use countdown timers for real promotions only</li><li>Monitor conversion rates and adjust</li></ul>`,
  },
  "Product Grid Setup": {
    section: "Feature Guides",
    htmlContent: `<p>Product grids showcase your products on the home page. Vexel includes primary and secondary grid options.</p><h2>Accessing Settings</h2><ol><li>Go to Home page in theme editor</li><li>Click on the <strong>Product Grid</strong> section</li></ol><h2>Key Settings</h2><ul><li><strong>Headline:</strong> Main section text</li><li><strong>Word to Highlight:</strong> Which word gets accent color</li><li><strong>Products Per Row:</strong> 2, 3, or 4 columns</li></ul><h2>Product Block Settings</h2><p>For each product:</p><ul><li><strong>Sale Badge:</strong> "HOT," "BEST SELLER," "NEW," etc. (1–2 words)</li><li><strong>Button Text:</strong> "Shop Now," "View Details," etc.</li><li><strong>Button Action:</strong> Product page, quick add to cart, or custom URL</li></ul><h2>What to Feature</h2><ul><li>Put your best-selling products first</li><li>New arrivals keep content fresh</li><li>High margin items improve profitability</li></ul><h2>Troubleshooting</h2><ul><li>Products not showing? Check they're published in Shopify and selected in the blocks</li><li>Wrong products? Clear and re-select them</li></ul>`,
  },
  "Reviews & Testimonials": {
    section: "Feature Guides",
    htmlContent: `<p>Display customer reviews and testimonials to build trust and increase conversions.</p><h2>Adding a Testimonials Section</h2><ol><li>Open the <strong>Theme Editor</strong></li><li>Click <strong>Add section</strong> on the homepage</li><li>Select <strong>Testimonials</strong></li><li>Add testimonial blocks (name, review text, star rating, photo)</li><li>Click <strong>Save</strong></li></ol><h2>Product Reviews</h2><p>Vexel is compatible with the Shopify Product Reviews app and <strong>Judge.me</strong>. Install either from the Shopify App Store to enable product-level reviews.</p><h2>Review Display</h2><p>Reviews appear on product pages below the product description. Average star ratings also show on collection page product cards.</p><h2>Getting More Reviews</h2><ul><li>Follow up with customers after purchase</li><li>Offer a small incentive for leaving a review</li><li>Link directly to the review form</li><li>Respond to all reviews professionally</li></ul>`,
  },
  "Troubleshooting Overview": {
    section: "Troubleshooting",
    htmlContent: `<p>If something isn't working as expected, start here.</p><h2>Most Common Issues</h2><ul><li><strong>License shows invalid</strong> — Check key is entered correctly in Theme Settings</li><li><strong>Theme not loading</strong> — Clear browser cache; check your internet</li><li><strong>Can't access account</strong> — Log in with your license key, not an email/password</li><li><strong>Didn't receive email</strong> — Check spam; wait up to 10 minutes</li></ul><h2>Quick Fixes</h2><ol><li><strong>Hard refresh:</strong> <code>Ctrl+Shift+R</code> (Windows) or <code>Cmd+Shift+R</code> (Mac)</li><li><strong>Clear cache:</strong> Clear browser cookies and cache</li><li><strong>Try incognito:</strong> Open in a private browser window</li><li><strong>Different browser:</strong> Try Chrome, Safari, or Firefox</li></ol><h2>Before Contacting Support</h2><p>Check the specific troubleshooting article for your issue first. If you still need help, use the chat widget — we usually respond within a few hours.</p>`,
  },
  "License Shows Invalid": {
    section: "Troubleshooting",
    htmlContent: `<p>If your store shows a license error, here's how to fix it.</p><h2>Step 1: Check Your License Key</h2><p>Go to <strong>Theme Editor → Theme Settings → License</strong>. Verify the key is: <code>XXXX-XXXX-XXXX-XXXX</code> with no extra spaces before or after.</p><h2>Step 2: Check Domain Binding</h2><p>Your license may be bound to a different store's auto-generated domain. If you recently created a new Shopify store, contact support to transfer the binding.</p><h2>Step 3: Check Your Account</h2><p>Log into your account on this site. Your license status should show "Active."</p><h2>Error Messages</h2><ul><li><strong>"Invalid license key"</strong> — The key format is wrong or doesn't exist. Copy it again carefully.</li><li><strong>"Domain mismatch"</strong> — License is on a different store. Contact support to transfer.</li></ul><h2>Still Not Working?</h2><p>Use the chat widget. Include your license key and your store's auto-generated domain (with numbers).</p>`,
  },
  "Theme Not Loading Properly": {
    section: "Troubleshooting",
    htmlContent: `<p>If Vexel is stuck on a loading screen or looks broken, try these steps in order.</p><h2>1. Hard Refresh</h2><p>Press <code>Ctrl+Shift+R</code> (Windows) or <code>Cmd+Shift+R</code> (Mac).</p><h2>2. Check License Key</h2><p>A missing or invalid license causes an endless loading screen. Go to <strong>Theme Editor → Theme Settings → License</strong> and confirm your key is there and correct.</p><h2>3. Try Incognito Mode</h2><p>Open your store in a private/incognito browser window. If it loads there, a browser extension is interfering.</p><h2>4. Check Your Internet</h2><p>The theme contacts our validation server. A slow or restricted network can cause the validation to time out.</p><h2>5. Try a Different Browser</h2><p>Test in Chrome, Safari, and Firefox to rule out a browser-specific issue.</p><h2>Contact Support</h2><p>If none of the above work, chat with us and include:</p><ul><li>Your store URL</li><li>Your license key</li><li>What you see (loading spinner, blank page, error message)</li><li>Which browser and device</li></ul>`,
  },
  "Can't Access My Account": {
    section: "Troubleshooting",
    htmlContent: `<p>Your Vexel account is accessed using your <strong>license key</strong>, not an email and password.</p><h2>How to Log In</h2><ol><li>Go to the <strong>Account</strong> page on this site</li><li>Enter your license key: <code>XXXX-XXXX-XXXX-XXXX</code></li><li>Click <strong>Log In</strong></li></ol><h2>Can't Find Your License Key?</h2><p>Search your inbox for "Vexel" or "license." Check your spam folder. It was sent to the email address you used at checkout.</p><h2>Common Issues</h2><ul><li><strong>"Invalid license key"</strong> — Copy the full key again with no extra spaces</li><li><strong>Login not working</strong> — Try a different browser or clear your cache</li></ul><h2>Still Can't Log In?</h2><p>Contact support via the chat widget with proof of purchase and we'll retrieve your license key for you.</p>`,
  },
  "Didn't Receive Email": {
    section: "Troubleshooting",
    htmlContent: `<p>If you didn't receive your purchase confirmation or license key email, here's what to do.</p><h2>1. Check Spam</h2><p>Check your spam or junk folder — payment processor emails often get filtered.</p><h2>2. Wait a Few Minutes</h2><p>Emails can take up to 10 minutes to arrive depending on your email provider.</p><h2>3. Check the Right Inbox</h2><p>Make sure you're checking the email address you used at checkout. If you have multiple, check them all.</p><h2>4. Search Your Inbox</h2><p>Search for "Vexel," "license," or "purchase."</p><h2>Still Nothing After 30 Minutes?</h2><p>Contact support via the chat widget. Include:</p><ul><li>The email address you used at checkout</li><li>The approximate time of purchase</li><li>Your order confirmation number (if you have it)</li></ul><p>We'll resend your license key manually.</p>`,
  },
  "Lite vs Pro Comparison": {
    section: "Plans & Policies",
    htmlContent: `<p>Both plans include the full Vexel theme and lifetime updates. Here's what's different.</p><table style="width:100%;border-collapse:collapse;margin:16px 0;font-size:13px"><thead><tr style="background:#f8fafc"><th style="padding:10px 12px;text-align:left;border:1px solid #e2e8f0">Feature</th><th style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">Lite ($179)</th><th style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">Pro ($379)</th></tr></thead><tbody><tr><td style="padding:10px 12px;border:1px solid #e2e8f0">Full theme with 140+ features</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">✓</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">✓</td></tr><tr style="background:#f8fafc"><td style="padding:10px 12px;border:1px solid #e2e8f0">Product image generator</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">✓</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">✓</td></tr><tr><td style="padding:10px 12px;border:1px solid #e2e8f0">Lifetime updates</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">✓</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">✓</td></tr><tr style="background:#f8fafc"><td style="padding:10px 12px;border:1px solid #e2e8f0">Store licenses</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">1</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">5</td></tr><tr><td style="padding:10px 12px;border:1px solid #e2e8f0">License transfer if banned</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">1 free</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">Unlimited</td></tr><tr style="background:#f8fafc"><td style="padding:10px 12px;border:1px solid #e2e8f0">1-on-1 full store setup</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">—</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">✓</td></tr><tr><td style="padding:10px 12px;border:1px solid #e2e8f0">Private Vexel community</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">—</td><td style="padding:10px 12px;text-align:center;border:1px solid #e2e8f0">✓</td></tr></tbody></table><h2>Which Should I Choose?</h2><p><strong>Lite:</strong> Just starting out and want to launch one store.</p><p><strong>Pro:</strong> Want multiple stores, hands-on setup help, or community access.</p>`,
  },
  "What If My Store Gets Banned?": {
    section: "Plans & Policies",
    htmlContent: `<p>Shopify sometimes bans stores. Here's how Vexel protects you.</p><h2>License Transfer</h2><p>If your store gets banned and you create a new one, contact support and we'll transfer your license to the new store's domain at no extra cost.</p><h2>Lite Plan</h2><p>Includes 1 store license with one free domain transfer. You can only use the license on one store at a time.</p><h2>Pro Plan</h2><p>Includes 5 store licenses with unlimited domain transfers. If one store gets banned, your other 4 licenses continue working and you can transfer the banned store's license to a new domain.</p><h2>How to Request a Transfer</h2><ol><li>Contact support via the chat widget</li><li>Provide your license key, the banned store's domain, and the new store's domain</li><li>We process transfers within 24 hours</li></ol><h2>Preventing Bans</h2><p>Common reasons Shopify bans stores: selling unauthorized branded goods, violating Shopify's ToS, too many chargebacks. Always ensure your store complies with Shopify's policies.</p>`,
  },
  "Using Vexel on Multiple Stores": {
    section: "Plans & Policies",
    htmlContent: `<p>Your plan determines how many stores you can run Vexel on simultaneously.</p><h2>Lite — 1 Store at a Time</h2><p>1 active store at a time. You can transfer to a new store (e.g., after a ban), but cannot run 2 stores simultaneously. Comes with 1 free transfer.</p><h2>Pro — Up to 5 Stores</h2><p>Up to 5 stores running Vexel simultaneously. Each store has its own domain binding. Domain transfers are unlimited.</p><h2>How Pro Multi-Store Works</h2><p>Your 5 Pro licenses can each be independently active on a different store. If one store gets banned, transfer that license to a new domain without affecting the other 4.</p><h2>Need More Than 5?</h2><p>Contact support via the chat widget to discuss custom licensing options for larger operations.</p>`,
  },
  "Refund Policy": {
    section: "Plans & Policies",
    htmlContent: `<p>Due to the digital nature of theme files, all sales are final once the theme has been downloaded.</p><h2>Before Purchasing</h2><p>We encourage you to:</p><ul><li>Review all documentation thoroughly</li><li>Contact support with any questions before buying</li><li>Make sure Vexel is the right fit for your store</li></ul><h2>Exceptions</h2><p>In rare cases where the theme is fundamentally broken and cannot be fixed through support, we may offer a refund at our discretion. Contact support within 7 days of purchase.</p><h2>What We Can Do Instead</h2><p>Most issues that would prompt a refund request can be resolved:</p><ul><li><strong>Technical problems</strong> → Contact support, we fix it</li><li><strong>Setup confusion</strong> → We walk through it with you</li><li><strong>Missing features</strong> → Check if the feature is in the documentation</li></ul><p>Before requesting a refund, please contact us — we're happy to help.</p>`,
  },
  "Contact & Support": {
    section: "Plans & Policies",
    htmlContent: `<p>We're here to help. Here's how to reach us.</p><h2>Chat Support (Fastest)</h2><p>Use the chat widget in the bottom-left corner of any page on this site. Enter your name, phone number, and message. We aim to respond within a few hours during business hours.</p><h2>Support Form</h2><p>Go to the <strong>Support</strong> page and fill in the form with your license key, store URL, and description of the issue.</p><h2>Response Times</h2><ul><li><strong>Chat messages:</strong> Usually within a few hours during business hours</li><li><strong>Support form:</strong> Within 24 hours</li><li><strong>Pro customers:</strong> Priority support with faster response times</li></ul><h2>What to Include</h2><ul><li>Your license key</li><li>Your store's auto-generated myshopify.com domain (with numbers)</li><li>Description of what you're seeing</li><li>Any error messages or screenshots</li></ul><h2>Before Contacting Us</h2><p>Please check the documentation first — most common questions are answered here. This helps us focus on cases that truly need human support.</p>`,
  },
};
